config/routes.rb
Rails.application.routes.draw do
  root 'docs#index'
  get 'docs/index'
  get 'docs/new'
  get 'docs/create'
  get 'docs/destroy'
  get 'docs/edit'
  devise_for :users
  resources :docs, only: [:index, :new, :create, :destroy, :edit]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  belongs_to :user
  
   validates :title, presence: true
   validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = current_user.docs.all
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.new(doc_params)
    @doc.user=current_user
   

    if @doc.save!
      redirect_to docs_path, notice: "The doc #{@doc.title} has been uploaded"
    else
      render "new"
    end
  end

  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy
    redirect_to docs_path, notice: "The doc #{@doc.title} has been deleted"
  end

  def edit
  end

private
  def set_doc
      @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :description, :tag1, :tag2, :attachment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/create.html.erb
<h1>Docs#create</h1>
<p>Find me in app/views/docs/create.html.erb</p>

app/views/docs/destroy.html.erb
<h1>Docs#destroy</h1>
<p>Find me in app/views/docs/destroy.html.erb</p>

app/views/docs/edit.html.erb
<h1>Docs#edit</h1>
<p>Find me in app/views/docs/edit.html.erb</p>

app/views/docs/index.html.erb
<div class = "container" style = "padding-top:20px; text-align:center">
<h1>File Uploader </h1>




<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "Upload New Doc", new_doc_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Title</th>
         
         <th>Description</th>
         
         <th>Tag 1</th>
         <th>Tag 2</th>
      </tr>
   </thead>
   
   <tbody>
      <% @docs.each do |doc| %>
         
         <tr>
            <td><%= doc.title %></td>
            <td><%= doc.description %></td>
            <td><%= doc.tag1 %></td>
            <td><%= doc.tag2 %></td>
            <td><%= button_to "Delete",  doc, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{doc.title}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>
<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
</div>

app/views/docs/new.html.erb
<div class = "container" style = "padding-top:20px; text-align:center">
<h1>Add New Doc</h1>


<% if !@doc.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @doc.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @doc, html: { multipart: true } do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= f.label :tag1 %>
      <%= f.text_field :tag1 %>
      <%= f.label :tag2 %>
      <%= f.text_field :tag2 %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Upload", class: "btn btn-primary" %>
   <% end %>
</div>
</div>

app/views/docs/show.html.erb
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Title</th>
         
         <th>Description</th>
         
         <th>Tag 1</th>
         <th>Tag 2</th>
      </tr>
   </thead>
   
   <tbody>
      <% @docs.each do |doc| %>
         
         <tr>
            <td><%= doc.title %></td>
            <td><%= doc.description %></td>
            <td><%= doc.tag1 %></td>
            <td><%= doc.tag2 %></td>
            <td><%= button_to "Delete",  doc, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{doc.title}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "container" style = "padding-top:20px;">
    <%= yield %>
    </div>
  </body>
</html>